theme = "tokyonight_nobg"

[editor]
true-color = true
line-number = "relative"
color-modes = true
cursorline = true
auto-save = true
bufferline = "multiple"
idle-timeout = 0

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = ""
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
C-q = ":x"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"C-n" = ["select_mode", "search_selection", "extend_search_next"]
"C-p" = ["select_mode", "search_selection", "extend_search_prev"]
"C-," = [":config-open"]
"A-w" = [":buffer-close"]
"'" = "repeat_last_motion"
"A-h" = "move_parent_node_start"
"A-l" = "move_parent_node_end"
"Y" = "yank_joined"
"C-b" = [":pipe xargs gh browse"]
"pageup" = "half_page_up"
"pagedown" = "half_page_down"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"C-n" = ["search_selection", "extend_search_next"]
"C-p" = ["search_selection", "extend_search_prev"]
"Y" = "yank_joined"

[keys.insert]
C-q = ":x"
C-z = "undo"
C-s = [":w", "normal_mode"]
C-e = "goto_line_end"
C-a = "goto_first_nonwhitespace"
A-d = "delete_word_forward"
C-d = "delete_char_forward"

[keys.normal.z]
"r" = ":reload"
"R" = ":reload-all"
"c" = ":config-reload"

[keys.normal.C-w]
"o" = "rotate_view"
"C-o" = "rotate_view"
"c" = "wonly"
