[[language]]
name = "env"
file-types = ["env"]

[[language]]
name = "ini"
file-types = ["conf", "ini", ".okta_aws_login_config", { suffix = ".aws/config" }, { suffix = ".aws/credentials" }]

[[language]]
name = "gotmpl"
file-types = ["tpl", "tmpl", "gotmpl"]

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = false

[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "python"
language-servers = [
  { name = "pyright" },
  { name = "ruff"}
]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[[language]]
name = "go"
roots = ["go.mod"]
