[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "python"
language-servers = [
  { name = "pyright", only-features = ["format", "diagnostics"] },
  { name = "python-lsp-server", except-features = ["format", "diagnostics"] },
]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
