[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "python"
language-servers = [
  { name = "pyright" },
]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
