format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$kubernetes\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

add_newline = false

[gcloud]
disabled = true
format = 'on [$symbol$account(@$domain)(/$project)(\($region\))]($style) '
style = "red"

[kubernetes]
disabled = true
format = "[$symbol$context]($style) "
style = "yellow bold"

[azure]
disabled = true

[time]
disabled = false

[git_status]
disabled = true

[character]
vimcmd_symbol = '[V](bold green) '

[hostname]
trim_at = ""
style = "red"
